### ISSUE TITLE
Package won't publish

### ISSUE THREAD

**Issue by cdm2012** [the-mac/integration_test_preview#2]
The package won't publish due to the pubspec.yaml device_preview git reference.

![Screen Shot 2022-03-27 at 8 56 18 AM](https://user-images.githubusercontent.com/1665162/160282570-97db40e8-e2bd-49f7-97e1-149d079ca1df.png)

This is the current pubspec.yaml:
```yaml
name: integration_test_preview
description: Integration Test Preview has pre-configured methods that allow for faster test deployment for end to end (e2e) test coverage (using Android and iOS platform UIs). This package is based upon the Integration Test Helper and Device Preview packages, and does much more with the combination of the two of them. It also allows for specific device size preview screenshots for the app stores, generated locally in your project path.
version: 0.0.1
homepage: https://github.com/the-mac/integration_test_preview

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  
  integration_test_helper: ^0.0.2

  device_preview:
    git:
      url: https://github.com/the-mac/flutter_device_preview.git
      path: device_preview/
      ref: master

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:

```
